import { StudentCourseSection } from '../../types/studentCourse';

export const mockStudentCourseSections: StudentCourseSection[] = [
  {
    id: 'section-001',
    sectionCode: 'CS101-01',
    courseCode: 'CS101',
    courseName: 'Nhập môn lập trình',
    credits: 3,
    departmentName: 'Công nghệ thông tin',
    description: 'Làm quen với tư duy lập trình, biến, cấu trúc điều khiển và hàm bằng ngôn ngữ Python.',
    lecturerName: 'Trần Bảo Long',
    semester: '2026A',
    capacity: 140,
    enrolledCount: 126,
    status: 'OPEN',
    schedules: [
      { dayOfWeek: 2, startTime: '07:30', endTime: '09:30', classroom: 'A1-201' },
      { dayOfWeek: 4, startTime: '07:30', endTime: '09:30', classroom: 'A1-201' },
    ],
  },
  {
    id: 'section-002',
    sectionCode: 'CS214-01',
    courseCode: 'CS214',
    courseName: 'Cấu trúc dữ liệu và giải thuật',
    credits: 4,
    departmentName: 'Công nghệ thông tin',
    description: 'Mảng, danh sách liên kết, ngăn xếp, hàng đợi, cây, đồ thị và các giải thuật sắp xếp, tìm kiếm.',
    lecturerName: 'Phạm Ngọc Linh',
    semester: '2026A',
    capacity: 96,
    enrolledCount: 96,
    status: 'FULL',
    schedules: [
      { dayOfWeek: 3, startTime: '09:45', endTime: '11:45', classroom: 'B2-105' },
      { dayOfWeek: 5, startTime: '09:45', endTime: '11:45', classroom: 'B2-105' },
    ],
  },
  {
    id: 'section-003',
    sectionCode: 'AI320-01',
    courseCode: 'AI320',
    courseName: 'Machine Learning cơ bản',
    credits: 3,
    departmentName: 'Trí tuệ nhân tạo',
    description: 'Hồi quy, phân loại, đánh giá mô hình và các thuật toán học máy nền tảng.',
    lecturerName: 'Lê Thu Hà',
    semester: '2026A',
    capacity: 72,
    enrolledCount: 54,
    status: 'OPEN',
    schedules: [{ dayOfWeek: 6, startTime: '13:00', endTime: '16:30', classroom: 'Lab-AI-02' }],
  },
  {
    id: 'section-004',
    sectionCode: 'MA101-02',
    courseCode: 'MA101',
    courseName: 'Giải tích 1',
    credits: 3,
    departmentName: 'Toán - Thống kê',
    description: 'Giới hạn, đạo hàm, tích phân và ứng dụng cho sinh viên các ngành kỹ thuật.',
    lecturerName: 'Nguyễn Văn Khoa',
    semester: '2026A',
    capacity: 120,
    enrolledCount: 118,
    status: 'OPEN',
    schedules: [
      { dayOfWeek: 2, startTime: '13:00', endTime: '15:00', classroom: 'C3-301' },
      { dayOfWeek: 5, startTime: '13:00', endTime: '15:00', classroom: 'C3-301' },
    ],
  },
  {
    id: 'section-005',
    sectionCode: 'EN201-01',
    courseCode: 'EN201',
    courseName: 'Tiếng Anh chuyên ngành CNTT',
    credits: 2,
    departmentName: 'Ngoại ngữ',
    description: 'Từ vựng và kỹ năng đọc tài liệu kỹ thuật, viết email và thuyết trình bằng tiếng Anh.',
    lecturerName: 'Đặng Minh Châu',
    semester: '2026A',
    capacity: 60,
    enrolledCount: 31,
    status: 'OPEN',
    schedules: [{ dayOfWeek: 4, startTime: '15:15', endTime: '17:15', classroom: 'D1-102' }],
  },
  {
    id: 'section-006',
    sectionCode: 'DB301-01',
    courseCode: 'DB301',
    courseName: 'Cơ sở dữ liệu',
    credits: 3,
    departmentName: 'Công nghệ thông tin',
    description: 'Mô hình quan hệ, SQL, chuẩn hóa dữ liệu và thiết kế cơ sở dữ liệu với PostgreSQL.',
    lecturerName: 'Hoàng Quốc Việt',
    semester: '2026A',
    capacity: 90,
    enrolledCount: 90,
    status: 'FULL',
    schedules: [
      { dayOfWeek: 3, startTime: '07:30', endTime: '09:30', classroom: 'B2-208' },
      { dayOfWeek: 6, startTime: '07:30', endTime: '09:30', classroom: 'B2-208' },
    ],
  },
  {
    id: 'section-007',
    sectionCode: 'PH102-01',
    courseCode: 'PH102',
    courseName: 'Vật lý đại cương 2',
    credits: 3,
    departmentName: 'Vật lý',
    description: 'Điện từ học, quang học và vật lý hiện đại ở mức đại cương.',
    lecturerName: 'Vũ Thị Mai',
    semester: '2026A',
    capacity: 100,
    enrolledCount: 44,
    status: 'CLOSED',
    schedules: [{ dayOfWeek: 7, startTime: '07:30', endTime: '11:00', classroom: 'E1-001' }],
  },
  {
    id: 'section-008',
    sectionCode: 'SE305-01',
    courseCode: 'SE305',
    courseName: 'Công nghệ phần mềm',
    credits: 3,
    departmentName: 'Công nghệ thông tin',
    description: 'Quy trình phát triển phần mềm, phân tích yêu cầu, thiết kế, kiểm thử và làm việc nhóm.',
    lecturerName: 'Trần Bảo Long',
    semester: '2026A',
    capacity: 80,
    enrolledCount: 47,
    status: 'OPEN',
    schedules: [
      { dayOfWeek: 3, startTime: '13:00', endTime: '15:00', classroom: 'A1-305' },
      { dayOfWeek: 5, startTime: '15:15', endTime: '17:15', classroom: 'A1-305' },
    ],
  },
];
