import { Course } from '../../types/course';

export const mockCourses: Course[] = [
  {
    id: 'course-001',
    code: 'CS101',
    title: 'Nhap mon lap trinh',
    lecturerName: 'Tran Bao Long',
    department: 'Computer Science',
    credits: 3,
    enrolledStudents: 126,
    capacity: 140,
    semester: '2026A',
    status: 'active',
    updatedAt: '2026-10-02',
  },
  {
    id: 'course-002',
    code: 'CS214',
    title: 'Cau truc du lieu va giai thuat',
    lecturerName: 'Pham Ngoc Linh',
    department: 'Computer Science',
    credits: 4,
    enrolledStudents: 88,
    capacity: 96,
    semester: '2026A',
    status: 'active',
    updatedAt: '2026-09-28',
  },
  {
    id: 'course-003',
    code: 'AI320',
    title: 'Machine Learning co ban',
    lecturerName: 'Le Thu Ha',
    department: 'Artificial Intelligence',
    credits: 3,
    enrolledStudents: 54,
    capacity: 72,
    semester: '2026A',
    status: 'draft',
    updatedAt: '2026-09-21',
  },
  {
    id: 'course-004',
    code: 'DB202',
    title: 'Co so du lieu',
    lecturerName: 'Dang Quoc Viet',
    department: 'Information Systems',
    credits: 3,
    enrolledStudents: 104,
    capacity: 110,
    semester: '2025B',
    status: 'archived',
    updatedAt: '2026-08-18',
  },
  {
    id: 'course-005',
    code: 'SE305',
    title: 'Cong nghe phan mem',
    lecturerName: 'Hoang Mai Chi',
    department: 'Software Engineering',
    credits: 3,
    enrolledStudents: 91,
    capacity: 100,
    semester: '2026A',
    status: 'active',
    updatedAt: '2026-10-04',
  },
];

