name: Frontend CI (Web/Mobile)

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'frontend/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Tạm thời comment lại. Bỏ comment khi team FE khởi tạo dự án.
      # - name: Cài đặt thư viện
      #   run: npm ci
      
      # - name: Kiểm tra Build (Web/Mobile)
      #   run: npm run build
